# 新建：configs/rtdetrv2/infer_r50vd.yml
task: detection

# 全局共享参数（仅推理需要）
use_focal_loss: True
num_classes: 15
eval_spatial_size: [640, 640]

model: RTDETR
postprocessor: RTDETRPostProcessor

RTDETR:
  backbone: PResNet
  encoder: HybridEncoder
  decoder: RTDETRTransformerv2

PResNet:
  depth: 50
  variant: d
  return_idx: [1, 2, 3]
  num_stages: 4
  freeze_norm: True
  pretrained: True

HybridEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'
  expansion: 1.0
  depth_mult: 1
  act: 'silu'

RTDETRTransformerv2:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3
  num_layers: 6
  num_queries: 300
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  eval_idx: -1
  num_points: [4, 4, 4]
  cross_attn_method: default
  query_select_method: default

RTDETRPostProcessor:
  num_top_queries: 300